name: Deploy

on:
  push:
    branches:
      - main
    pull_request: {}

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up node
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Set up workspace cache
        uses: ./.github/actions/with-cached-workspace

  pages:
    name: Pages
    runs-on: ubuntu-latest
    needs: setup

    permissions:
      contents: write

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download workspace cache
        uses: ./.github/actions/with-cached-workspace

      - name: Building
        run: npm run build

      - name: Deploying to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
